# A simple list of EU member states for the type-ahead. Format: "Display Name|CODE"
# updated as per https://confluence.tools.tax.service.gov.uk/spaces/RBD/pages/1255442163/Preferences+Mapping
eu.member-states = [
  "Austria|AT",
  "Belgium|BE",
  "Bulgaria|BG",
  "Canary Islands|IC",
  "Ceuta|XI",
  "Croatia|HR",
  "Cyprus|CY",
  "Czech Republic|CZ",
  "Denmark|DK",
  "Estonia|EE",
  "Finland|FI",
  "France|FR",
  "Germany|DE",
  "Greece|EL",
  "Hungary|HU",
  "Ireland|IE",
  "Italy|IT",
  "Latvia|LV",
  "Lithuania|LT",
  "Luxembourg|LU",
  "Malta|MT",
  "Melilla|XJ",
  "Monaco|MC",
  "Netherlands|NL",
  "Poland|PL",
  "Portugal|PT",
  "Romania|RO",
  "Slovakia|SK",
  "Slovenia|SI",
  "Spain|ES",
  "Sweden|SE"
]
